server:
  address:     ":8000"
  openapiPath: "/api.json"
  swaggerPath: "/swagger"

logger:
  level : "all"
  stdout: true

# 数据库连接配置
database:
  logger:
    path:    "temp/logs/sql"
    level:   "all"
    stdout:  true
    ctxKeys: ["RequestId"]

  default:
    # link:   "mysql:root:12345678@tcp(127.0.0.1:3306)/focus"
    link:   "mysql:root:123456@tcp(127.0.0.1:3306)/my_shop?loc=Local"
    debug:  true


# Redis 配置示例
redis:
  # 单实例配置示例1
  default:
    address: 127.0.0.1:6379
    db:          1
    pass:        123456
    idleTimeout: 600

#qiniu:

upload:
  path: "upload"